name: mesomb
description: Dart client to perform mobile payment transaction with MeSomb.
 you can integrate the module into your application for payments
version: 2.0.1
homepage: https://mesomb.com

environment:
 sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
 lints: ^3.0.0
 test: ^1.16.0

dependencies:
 crypto: ^3.0.6
 http: '>=1.1.0 <2.0.0'