name: mesomb
description: Dart client to perform mobile payment operation with MeSomb
version: 1.0.0
homepage: https://mesomb.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5