class Wallet {
  Map<String, dynamic> _data;

  /// The wallet's id generated by MeSomb
  late int id;

  /// The wallet owner's number
  late String number;

  /// The wallet owner's country
  late String country;

  /// The wallet owner's status
  late String status;

  /// The last activity on the wallet
  late DateTime? lastActivity;

  /// The wallet owner's balance
  late double? balance;

  /// The wallet owner's first name
  late String? firstName;

  /// The wallet owner's last name
  late String lastName;

  /// The wallet owner's email
  late String? email;

  /// The wallet owner's phone number
  late String phoneNumber;

  /// The wallet owner's gender
  late String gender;

  Wallet(this._data)
      : id = _data['id'],
        number = _data['number'],
        country = _data['country'],
        status = _data['status'],
        lastActivity = _data['last_activity'] != null ? DateTime.tryParse(_data['last_activity']) : null,
        balance = _data['balance'],
        firstName = _data['first_name'],
        lastName = _data['last_name'],
        email = _data['email'],
        phoneNumber = _data['phone_number'],
        gender = _data['gender'];

  Map<String, dynamic> getData() => _data;
}
